stage_1:
  target: stage1.UAE
  ckpt: 'results/siglip2/stage1/siglip2_stage_1/checkpoints/ep-last.pt'
  params:
    encoder_cls: 'SigLIP2wNorm'
    encoder_config_path: 'google/siglip2-base-patch16-256'
    encoder_input_size: 256
    encoder_params:
      model_name: 'google/siglip2-base-patch16-256'
    decoder_config_path: 'configs/decoder/ViTXL'
    noise_tau: 0.8
    reshape_to_2d: true
    frequency_config:
      freq_order: zigzag
      freq_transform: dct
      band_split:
        enabled: true
        mode: low
        count: 128
        apply_prob: 0.5
        uniform: true
        count_min: 128
        count_max: 256
        per_sample: true



training:
  epochs: 17
  ema_decay: 0.9978
  encoder_trainable: true
  encoder_lr_ratio: 1.0
  global_batch_size: 512
  num_workers: 8
  clip_grad: 0.0
  log_interval: 100
  checkpoint_interval: 1 
  sample_every: 2500
  optimizer:
    lr: 2.0e-5
    betas: [0.9, 0.95]
    weight_decay: 0.0
  scheduler:
    type: cosine
    warmup_epochs: 1
    decay_end_epoch: 17
    base_lr: 2.0e-4
    final_lr: 2.0e-5
    warmup_from_zero: true
  band_reg:
    enabled: true
    weight: 0.5
    mode: soft
    freq_transform: dct
    first_tokens: 128
    token_order: zigzag
    soft_curve: power
    soft_power: 1.0
    soft_mid: 0.2
    soft_min_weight: 0.0
  clean_recon:
    enabled: true
    l1_weight: 10.0
    lpips_weight: 10.0

eval:
  eval_interval: 2500
  eval_model: true
  data_path: PATH_TO_IMAGENET_VAL
  reference_npz_path: 'downloads/data/val_ImageNet.npz'
  metrics: ['psnr', 'ssim', 'rfid']

gan:
  disc:
    arch:
      dino_ckpt_path: 'downloads/discs/dino_vit_small_patch8_224.pth'
      ks: 9
      norm_type: 'bn'
      using_spec_norm: true
      recipe: 'S_8'
    optimizer:
      lr: 2.0e-5
      betas: [0.9, 0.95]
      weight_decay: 0.0
    scheduler:
      type: cosine
      warmup_epochs: 1
      decay_end_epoch: 17
      base_lr: 2.0e-4
      final_lr: 2.0e-5
      warmup_from_zero: true
    augment:
      prob: 1.0
      cutout: 0.0
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: 0.75
    perceptual_weight: 1.0
    disc_start: 8
    disc_upd_start: 6
    lpips_start: 0
    max_d_weight: 10000.0
    disc_updates: 1
